apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-awesome-app-secrets
  namespace: default
spec:
  refreshInterval: 2h
  secretStoreRef:
    name: servercore-webhook-backend
    kind: ClusterSecretStore
  target:
    name: my-awesome-app-secrets
    creationPolicy: Owner
  data:
  - secretKey: database_url
    remoteRef:
      key: my-awesome-app-secrets
      property: database_url
  - secretKey: api_key
    remoteRef:
      key: my-awesome-app-secrets
      property: api_key
  - secretKey: jwt_secret
    remoteRef:
      key: my-awesome-app-secrets
      property: jwt_secret
  - secretKey: redis_password
    remoteRef:
      key: my-awesome-app-secrets
      property: redis_password
  - secretKey: smtp_password
    remoteRef:
      key: my-awesome-app-secrets
      property: smtp_password